---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
      time: "06:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
